baseURL = 'https://avd151.github.io/csblog/'
languageCode = 'en-us'
title = 'Exploring Computer Science'
theme = 'aether'

[params]
description = "Blog to document my learnings in Computer Science and Software Engineering"
github = "https://github.com/avd151"
linkedin = "https://linkedin.com/in/apurva151"

[markup]
  [markup.highlight]
    style = "igor"
