baseURL = 'https://avd151.github.io/csblog/'
languageCode = 'en-us'
title = 'Computer Science Blog'
theme = 'aether'

[params]
description = "Blog to share my learnings in Computer Science, Software Development and Machine Learning"
github = "https://github.com/avd151"
linkedin = "https://linkedin.com/in/avd151"

[markup]
  [markup.highlight]
    style = "igor"